# Generated by Django 3.2.5 on 2021-07-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210713_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='name',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
