# Generated by Django 3.2.5 on 2021-07-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='color',
            field=models.CharField(default=1234, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='icon',
            field=models.ForeignKey(default=12324, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounts', to='account.icon'),
            preserve_default=False,
        ),
    ]
