# Generated by Django 3.2.5 on 2021-07-14 06:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210713_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounts', to='account.account')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounts', to='account.transaction_type')),
            ],
        ),
    ]
