# Generated by Django 3.2.5 on 2021-07-14 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210714_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
