# Generated by Django 3.2.5 on 2021-07-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_transaction_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
