# Generated by Django 3.2.5 on 2021-07-15 06:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_transaction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='iamge'),
        ),
    ]
